"""initial

Revision ID: e786b45d428f
Revises: 
Create Date: 2026-05-15 11:34:44.227186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e786b45d428f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('nit', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('acto_administrativo', sa.Text(), nullable=True),
    sa.Column('separator', sa.String(length=1), nullable=True),
    sa.Column('is_centralized', sa.Boolean(), nullable=True),
    sa.Column('central_dependency_code', sa.String(length=100), nullable=True),
    sa.Column('representante_legal_nombre', sa.String(length=255), nullable=True),
    sa.Column('representante_legal_cargo', sa.String(length=255), nullable=True),
    sa.Column('nom_responsable_gestion_documental', sa.String(length=255), nullable=True),
    sa.Column('cgo_responsable_gestion_documental', sa.String(length=255), nullable=True),
    sa.Column('dep_responsable_gestion_documental', sa.String(length=255), nullable=True),
    sa.Column('functions', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities')
    # ### end Alembic commands ###
